---

- name: "Build docker images and push it to the repository"
  hosts: localhost
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:

    - name: "create a local temp directory which will have the dockerfiles"
      command: mktemp -d "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}/ansible.XXXX"
      register: mktemp_output
      check_mode: no

    - name: "Prepare the docker files and artifacts needed for docker image build"
      include_tasks: "includes/prepare-docker-artifacts.yml artifact_directory={{ mktemp_output.stdout }} microservice={{ item }}"
      with_items:
        - eureka-server
        - chatbot
        - webclient

    - name : "Build docker images for each of the microservice and push it to the repository"
      docker_image :
        path : "{{ mktemp_output.stdout }}"
        dockerfile: "{{ item }}-Dockerfile"
        name : "guru/{{ item }}"
        tag: test
      with_items:
        - eureka-server
        - chatbot
        - webclient

    - name: "Cleaning up the temp directory"
      file:
        path: "{{ mktemp_output.stdout }}/"
        state: absent
