### Spring properties
# Service registers under this name
spring:
  application:
    name: executer-ms

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: executer
      friendlyname: Executer
    hostName: ${EXECUTOR_PUBLISH_HOST:localhost} 
    preferIpAddress: false 
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST:localhost}:${EUREKA_SERVICE_PORT:8761}/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: ${EXECUTOR_PUBLISH_PORT:2500}

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
