matrix:
  include:
    - language: java
      jdk:
        - oraclejdk8
        - oraclejdk9
        - openjdk8

      install: true

     script:
       - mvn clean install -DSkiptests
    
    - language: python
      install:
        - pip install ansible==2.2.2.0
      script: pytest
