
sudo: required
language: java
jdk:
  - oraclejdk8

install: true

script:
- mvn clean install -DskipTests -q -P linux

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - stage: deploy
      sudo: required
      dist: trusty
      python: "2.7"
      services:
      - docker
      addons:
        ssh_known_hosts:
        - 131.234.29.7

      before_install:
      - openssl aes-256-cbc -K $encrypted_a09f00fca840_key -iv $encrypted_a09f00fca840_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
      - eval "$(ssh-agent -s)"
      - chmod 600 /tmp/deploy_rsa
      - ssh-add /tmp/deploy_rsa

      install:
      - pip install ansible===2.4.0.0
      script:
      - ansible-playbook -i playbook/inventory/sask_dev.inventory playbook/deploy_microservices.yml --extra-vars "image_tag=91a1f96a418912108dc4e9f4dc5be5cf5a03e3ad"

