matrix:
  include:
    - language: java

      java: "oraclejdk8"
      env: TEST_SUITE = suite_oraclejdk8

      java: "oraclejdk9"
      env: TEST_SUITE = suite_oraclejdk9

      java: "openjdk8"
      env: TEST_SUITE = suite_openjdk8

      script:
        - mvn clean install -q -P linux $TEST_SUITE

    - sudo: required

      language: python
      python: "2.7"

      before_install:
        - sudo apt-get update -qq
     
      install:
        - pip install ansible

      script:
        - ansible-playbook -i playbook/inventory/dev.inventory playbook/build-images.yml