### Spring properties
# Service registers under this name
spring:
  application:
    name: exception-ms

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: logging
      friendlyname: Logging
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 9601

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false