---
## File defines the sask microservices details

# vars file for modules

microservices:
  - chatbot
  - eureka-server
  - webclient

image_tag: "latest"

## Eureka Service Related properties -- START

eureka_service_port: 8761

eureka_service_host: "{{ groups['eureka-server']| join(',') }}"

## Eureka Service Related properties -- END


## Chatbot Service Related properties -- START
chatbot_instance_base_port: 9191

#TODO: This value should be updated to the correct HAWK endpoint
qa_hawk_url: "http://185.2.103.92:8081/tebaqa/qa-simple?query="

#TODO: This value should be updated to the correct SESS endpoint
sessa_search_url: "http://localhost:7070/search?query="

## Chatbot Service Related properties -- END


## WebClient Service Related properties -- START
webclient_instance_base_port: 9090


## WebClient Service Related properties -- END 
