---
# tasks file for modules\

- name: "create a local temp directory which will have the dockerfiles"
  command: mktemp -d "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}/ansible.XXXX"
  register: mktemp_output
  check_mode: no

- name: "Prepare the docker files and artifacts needed for docker image build"
  include_tasks: "{{ playbook_dir }}/includes/prepare-docker-artifacts.yml artifact_directory={{ mktemp_output.stdout }} microservice={{ item }}"
  with_items:
    - eureka-server
    - chatbot
    - webclient

- name: "Login to the docker registry"
  docker_login: 
    username: guru5590
    password: Phoenix.07
    email: guru5590@gmail.com

- name : "Build docker images for each of the microservice and push it to the repository"
  docker_image :
    path : "{{ mktemp_output.stdout }}"
    dockerfile: "{{ item }}-Dockerfile"
    name : "guru5590/{{ item }}"
    tag: latest
    push: yes
    with_items:
      - eureka-server
      - chatbot
      - webclient

- name: "Logout of docker hub"
  docker_login:
    state: absent
    email: guru5590@gmail.com

- name: "Cleaning up the temp directory"
  file:
    path: "{{ mktemp_output.stdout }}/"
    state: absent