# Configure this Discovery Server
eureka:
  instance:
    hostname: eureka
  client: #Not a client
    registerWithEureka: false
    fetchRegistry: false

# HTTP (Tomcat) port
server:
  port: 1111   
