# Configure this Discovery Server
eureka:
  instance:
    hostname: ${EUREKA_SERVICE_HOST:localhost}
  client: #Not a client
    registerWithEureka: false
    fetchRegistry: false

# HTTP (Tomcat) port
server:
  port: ${EUREKA_SERVICE_PORT:1111}   
